### ISSUE TITLE
indexer doesn't run

### ISSUE THREAD

**Issue by wliao008** [samj1912/ltr-demo#12]
i was following the steps, stuck on step 5.
```
 [61] → docker-compose up indexer                                                                                                   
ltr-demo_solr_1 is up-to-date                                                                                                       
Creating ltr-demo_indexer_1 ... done                                                                                                
Attaching to ltr-demo_indexer_1                                                                                                     
indexer_1  | Deleting existing index...                                                                                             
indexer_1  | Reading input file...                                
indexer_1  | Input loaded.                                                                                                          indexer_1  | Document indexing in progress...                     
indexer_1  | concurrent.futures.process._RemoteTraceback:                                                                           indexer_1  | """                                                  
indexer_1  | Traceback (most recent call last):                                                                                     indexer_1  |   File "/usr/local/lib/python3.7/concurrent/futures/process.py", line 239, in _process_worker
indexer_1  |     r = call_item.fn(*call_item.args, **call_item.kwargs)                                                              indexer_1  |   File "/usr/local/lib/python3.7/concurrent/futures/process.py", line 198, in _process_chunk
indexer_1  |     return [fn(*args) for args in chunk]                                                                               indexer_1  |   File "/usr/local/lib/python3.7/concurrent/futures/process.py", line 198, in <listcomp>
indexer_1  |     return [fn(*args) for args in chunk]                                                                               indexer_1  |   File "indexer.py", line 64, in process_articles    
indexer_1  |     solr.add(processed_articles)                                                                                       indexer_1  |   File "/usr/local/lib/python3.7/site-packages/pysolr.py", line 1020, in add                                           
indexer_1  |     raise ValueError("wrong message type")                                                                             indexer_1  | ValueError: wrong message type                                                                                         
indexer_1  | """                                                                                                                    indexer_1  |                                                                                                                        
indexer_1  | The above exception was the direct cause of the following exception:                                                   indexer_1  |                                                                                                                        
indexer_1  | Traceback (most recent call last):                                                                                     
indexer_1  |   File "indexer.py", line 90, in <module>                                                                              
indexer_1  |     cli()                                            
indexer_1  |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
indexer_1  |     return self.main(*args, **kwargs)
indexer_1  |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
indexer_1  |     rv = self.invoke(ctx)
indexer_1  |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
indexer_1  |     return _process_result(sub_ctx.command.invoke(sub_ctx))
indexer_1  |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
indexer_1  |     return ctx.invoke(self.callback, **ctx.params)
indexer_1  |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
indexer_1  |     return callback(*args, **kwargs)
indexer_1  |   File "indexer.py", line 85, in index_collection
indexer_1  |     for task in tasks:
indexer_1  |   File "/usr/local/lib/python3.7/site-packages/click/_termui_impl.py", line 315, in generator
indexer_1  |     for rv in self.iter:
indexer_1  |   File "/usr/local/lib/python3.7/concurrent/futures/process.py", line 483, in _chain_from_iterable_of_lists
indexer_1  |     for element in iterable:
indexer_1  |   File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 598, in result_iterator
indexer_1  |     yield fs.pop().result()
indexer_1  |   File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 435, in result
indexer_1  |     return self.__get_result()
indexer_1  |   File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
indexer_1  |     raise self._exception
indexer_1  | ValueError: wrong message type
ltr-demo_indexer_1 exited with code 1
```

**Comment by wliao008** [comment]
From looking at pysolr.py, I got around it a bit by changing
```
solr.add(processed_articles)
```
to
```
solr.add(list(processed_articles))
```
the indexer container would index about 180k docs before it failed with timeout to the solr.

I also tried changing the SOLR_URL to localhost:8983 and ran the following
```
python3 indexer.py index --input simple-wikipedia.json.gz 
```
This didn't produce any error and it seems to index the same amount of docs, so I'll leave it at that and carry on.
